```{r library, include=FALSE}
my_packages <- c("tidyverse", "data.table",
                 "plyr", "GSEABase")
pacman::p_load(char = my_packages)

tmp <- list()
```

# Survival data
## TCGA
```{r}
pan_clinical_all <- fread("Input/Dataset/Survival_SupplementalTable_S1_20171025_xena_sp.txt")
tcga_survival <- pan_clinical_all[,c(2,3,26,27)]
tcga_survival <- unique(tcga_survival)

colnames(tcga_survival)[1:2] <- c("Patient", "Project")
head(tcga_survival)
```

## Target
```{r}
WT_clinical <- fread("Input/Dataset/Target/TARGET-WT.clinical.tsv.gz")
OS_clinical <- fread("Input/Dataset/Target/TARGET-OS.clinical.tsv.gz")
NBL_clinical <- fread("Input/Dataset/Target/TARGET-NBL.clinical.tsv.gz")
AML_clinical <- fread("Input/Dataset/Target/TARGET-AML.clinical.tsv.gz")
ALL_clinical <- fread("Input/Dataset/Target/TARGET-ALL-P3.clinical.tsv.gz")

# WT
WT_clinical <- WT_clinical[,c(2,
                              7:10)]
WT_clinical$`First Event` <- ifelse(
  WT_clinical$`First Event` %in% "None",
  0, 1
)
WT_clinical$`Vital Status` <- ifelse(
  WT_clinical$`Vital Status` %in% "Alive",
  0, 1
)
colnames(WT_clinical) <- c("patient",
                           "EFS", "EFS.time",
                           "OS", "OS.time"
                           )
# OS
OS_clinical <- OS_clinical[,c(2,
                              7:10)]
colnames(OS_clinical) <- c("patient",
                           "EFS", "EFS.time",
                           "OS", "OS.time"
                           )
OS_clinical$EFS <- case_when(
    OS_clinical$EFS %in% c("No event", "None") ~ 0,
    OS_clinical$EFS %in% "" ~ 2,
    TRUE ~ 1
  )
OS_clinical$EFS[OS_clinical$EFS %in% 2] <- NA
OS_clinical$OS <- case_when(
    OS_clinical$OS %in% c("Alive") ~ 0,
    OS_clinical$OS %in% "" ~ 2,
    TRUE ~ 1
  )
OS_clinical$OS[OS_clinical$OS %in% 2] <- NA

# NBL
NBL_clinical <- NBL_clinical[,c(2,
                              7:10)]
colnames(NBL_clinical) <- c("patient",
                           "EFS", "EFS.time",
                           "OS", "OS.time"
                           )
NBL_clinical$EFS <- case_when(
    NBL_clinical$EFS %in% c("Censored") ~ 0,
    NBL_clinical$EFS %in% "Unknown" ~ 2,
    TRUE ~ 1
  )
NBL_clinical$EFS[NBL_clinical$EFS %in% 2] <- NA
NBL_clinical$OS <- case_when(
    NBL_clinical$OS %in% c("Alive") ~ 0,
    NBL_clinical$OS %in% "Unknown" ~ 2,
    TRUE ~ 1
  )
NBL_clinical$OS[NBL_clinical$OS %in% 2] <- NA

# AML
AML_clinical <- AML_clinical[,c(2,
                              7:10)]
colnames(AML_clinical) <- c("patient",
                           "EFS", "EFS.time",
                           "OS", "OS.time"
                           )
AML_clinical$EFS <- case_when(
    AML_clinical$EFS %in% c("Censored") ~ 0,
    AML_clinical$EFS %in% "" ~ 2,
    TRUE ~ 1
  )
AML_clinical$EFS[AML_clinical$EFS %in% 2] <- NA
AML_clinical$OS <- case_when(
    AML_clinical$OS %in% c("Alive") ~ 0,
    AML_clinical$OS %in% "" ~ 2,
    TRUE ~ 1
  )
AML_clinical$OS[AML_clinical$OS %in% 2] <- NA

# AML
ALL_clinical <- ALL_clinical[,c(2,
                              5:8)]
colnames(ALL_clinical) <- c("patient",
                           "EFS", "EFS.time",
                           "OS", "OS.time"
                           )
ALL_clinical$EFS <- case_when(
    ALL_clinical$EFS %in% c("None") ~ 0,
    TRUE ~ 1
  )
ALL_clinical$OS <- case_when(
    ALL_clinical$OS %in% c("Alive") ~ 0,
    ALL_clinical$OS %in% "" ~ 2,
    TRUE ~ 1
  )
ALL_clinical$OS[ALL_clinical$OS %in% 2] <- NA
ALL_clinical$EFS[ALL_clinical$OS %in% 1] <- 1
```

```{r}
target_survival <- rbind(
  ALL_clinical,
  AML_clinical,
  NBL_clinical,
  OS_clinical,
  WT_clinical
)
target_survival <- unique(target_survival)
```

```{r}
head(target_survival)
```

```{r}
target_survival$Project <- substr(target_survival$patient,
                                  1, 9)
table(target_survival$Project)
```

```{r}
target_survival$Project <- mapvalues(
  target_survival$Project,
  c("TARGET-15", "TARGET-20", "TARGET-21",
    "TARGET-30", "TARGET-40", "TARGET-50"),
  c("TARGET-ALL", "TARGET-AML", "TARGET-AML",
    "TARGET-NBL", "TARGET-OS", "TARGET-WT")
)

table(target_survival$Project)
```

```{r}
target_survival <- target_survival[,c(1,6,4,5)]
colnames(target_survival)[1] <- "Patient"
```

```{r}
pan_survival <- rbind(tcga_survival, target_survival)
pan_survival <- unique(pan_survival)
head(pan_survival)
```

```{r}
table(pan_survival$Project)
```


# RNA data
## RNA process
```{r}
pan_RNA <- fread("Input/GDC-PANCAN.htseq_fpkm-uq.tsv.gz")
pan_RNA$xena_sample <- substr(pan_RNA$xena_sample, 1, 15)

gtf_RNA <- fread("Input/gencode.v41.annotation.csv")
gtf_RNA$gene_id <- substr(gtf_RNA$gene_id, 1, 15)
```

mRNA:
```{r}
mRNA.gtf <- unique(gtf_RNA[,c(10,11,12)])
mRNA.gtf <- mRNA.gtf[mRNA.gtf$gene_type %in% "protein_coding",]
pan_mRNA <- merge(pan_RNA, mRNA.gtf[,c(1,3)], by.x = "xena_sample",
                  by.y = "gene_id")
pan_mRNA$xena_sample <- NULL
pan_mRNA <- gather(data = pan_mRNA,
                       key = name,
                       value = exp,
                       - gene_name)
pan_mRNA <- dcast(data.table(pan_mRNA), gene_name~name,
                 value.var="exp", fun.aggregate = max)

pan_mRNA <- as.data.frame(pan_mRNA); rownames(pan_mRNA) <- pan_mRNA$gene_name
pan_mRNA$gene_name <- NULL
```

## Split
filter patient with survival info:
```{r}
pan_anno_df <- data.frame(
    sample = colnames(pan_RNA)
)
pan_anno_df$patient <- substr(pan_anno_df$sample, 1, nchar(pan_anno_df$sample)-4)
```

```{r}
pan_anno_df2 <- merge(pan_anno_df, pan_survival, by.x = "patient", by.y = "Patient")
pan_anno_df2 <- unique(pan_anno_df2)
```

```{r}
pan_anno_list <- split(pan_anno_df2, pan_anno_df2$patient)
```

```{r}
lapply(pan_anno_list, function(project){
    mRNA <- pan_mRNA[,colnames(pan_mRNA) %in% project$sample]
    saveRDS(mRNA, file = paste0("Output/Steps/R01/pan_RNA_exp/", project$Project[1], ".Rds"))
})
```


# Msigdb

```{r}
all_list <- getGmt("Input/Msigdb/msigdb.v2022.1.Hs.symbols.gmt")
```

```{r}
msigdb_name <- names(all_list)
table(grepl("HALL", msigdb_name))

msigdb_name_df <- data.frame(names = msigdb_name)
```

```{r}
test_pathway <- all_list[grepl("HALLMARK_", names(all_list))]
```

## Select pathways

- hallmark 50
- KEGG 186
- reactome 1635
- BIOCARTA 292
- PID 196
- wiki 712
- GOBP 7763, CC 1035, MF 1763


```{r}
selected_pathways <- all_list[grepl("HALLMARK_|KEGG_|^GOBP_|^GOCC_|^GOMF_", names(all_list))]

selected_pathways_df <- data.frame(names = names(selected_pathways))
```

# Save
```{r}
saveRDS(pan_survival, 
        file = "Output/Steps/R01/pan_survival.Rds")
```

```{r}
saveRDS(pan_anno_df2,
     file = "Output/Steps/R01/pan_anno.Rds")
```

```{r}
saveRDS(selected_pathways,
        file = "Output/Steps/R01/msigdb_selected_pathways.Rds")
```

