```{r library, include=FALSE}
my_packages <- c("tidyverse", "data.table",
                 "withr",
                 "ggpubr", "patchwork")
pacman::p_load(char = my_packages)

tmp <- list()
```

# Load data
```{r}
tmp$res_list <- paste0("Output/output_v1/", list.files("Output/output_v1/"))
with_seed(seed = 66, tmp$res_list2 <- sample(tmp$res_list, 100))
# tmp$res_list2 <- tmp$res_list

res_list <- lapply(1:length(tmp$res_list2), function(x){
  res_df <- fread(tmp$res_list2[x])
  res_df$Pathway <- gsub("Output/output_v1/", "", tmp$res_list2[x])
  res_df$Pathway <- gsub(".csv", "", res_df$Pathway)
  return(res_df)
})
res_df <- do.call(rbind, res_list)
res_df2 <- res_df[res_df$Training > 0.7 & res_df$Testing > 0.7,]
```

# Statistics
```{r}
res_df3 <- unique(res_df2[,c("method", "Type", "Pathway")])
rank_pathway <- res_df3 %>% group_by(Type, method) %>% dplyr::summarise(counts = n())
```

```{r}
p5 <- ggplot(rank_pathway, aes(x = Type, 
                     y = counts,
                     fill = method)) + geom_col(position = position_dodge2(preserve = "single")) + geom_text(aes(label = counts), position = position_dodge2(width = 0.9, preserve = "single"), vjust = -0.8) + theme_bw() + theme(
                       axis.title.x = element_blank(),
                       axis.text.x = element_text(angle = 90)
                     )  + scale_fill_manual(values = rev(paletteer::paletteer_d("RColorBrewer::Set3")))
p5                   
```


# High frequent pathways of top AUC pathways 
```{r}
rank_pathway2 <- res_df2 %>% group_by(Type, Pathway) %>% dplyr::summarise(median_AUC = median(AUC))
rank_pathway2
```


```{r}
res_list <- split(rank_pathway2, rank_pathway2$Type)
res_list2 <- lapply(res_list, function(x){
  aa <- x[order(x[,"median_AUC"], decreasing = T),]
  head(aa$Pathway, 20)
})

pathway_df <- lapply(1:36, function(x){
  df <- data.frame(
    pathway = res_list2[[x]],
    type = names(res_list2)[x]
  )
})
pathway_df <- do.call(rbind, pathway_df)
```

```{r}
re <- table(pathway_df$pathway)
re <- re[order(re)]

tail(re, 10)
```

# High frequent pathways of all
```{r}
re2 <- table(rank_pathway2$Pathway)
re2 <- re2[order(re2)]
re2[re2>=33]
```

# select genes
```{r}
tmp$sel_types <- pathway_df[pathway_df$pathway %in% "GOMF_TRANSPORTER_ACTIVITY",]$type

res_df3 <- res_df2[res_df2$Type %in% tmp$sel_types,]
res_df3$Type <- as.character(res_df3$Type)
table(res_df3$Type)

res_df3_1 <- unique(res_df3[,c("genes", "Type")])
```

```{r}
genes_list <- split(res_df3, res_df3$Type)
```

```{r}
genes_list2 <- lapply(genes_list, function(x){
    g <- x$genes
    g <- strsplit(g, ", ")
    g2 <- lapply(1:length(g), function(y){
    data.frame(
        genes = g[[y]],
        type = x$Type[1],
        index = y
    )
    })
    g2 <- do.call(rbind, g2)
    return(g2)
})
res_df3_2 <- do.call(rbind, genes_list2)
```

```{r}
res_tab <- table(res_df3_2$genes)/nrow(res_df3_2)

cat(names(head(res_tab[order(res_tab, decreasing = T)], 10)), sep = ", ")
```



